#!/usr/bin/env python3
"""Generate the web console's data files from the Python package.

Two outputs, both committed:

  web/src/catalog.data.js   the capability catalogs and sample engagements the
                            browser app runs on -- generated so the app can
                            never drift from `scvr/catalog.py`
  tests/fixtures/parity.json  the reference outputs the JS engine is checked
                            against by tests/test_web_parity.js

    python3 tools/gen_web_data.py
"""

from __future__ import annotations

import dataclasses
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from scvr import catalog
from scvr.audit import run
from scvr.model import Engagement

ROOT = Path(__file__).resolve().parent.parent
CATALOG_OUT = ROOT / "web" / "src" / "catalog.data.js"
FIXTURE_OUT = ROOT / "tests" / "fixtures" / "parity.json"

EXAMPLES = [
    "examples/client-zero-northgate-3pl.json",
    "examples/harborlink-3pl.json",
    "examples/meridian-cold-chain.json",
    "examples/valeron-distribution.json",
]


def catalog_payload() -> dict:
    return {
        platform: [dataclasses.asdict(cap) for cap in catalog.get_catalog(platform)]
        for platform in catalog.platforms()
    }


def write_catalog_js() -> None:
    samples = [json.loads((ROOT / path).read_text(encoding="utf-8")) for path in EXAMPLES]
    body = {
        "catalogs": catalog_payload(),
        "platformNames": catalog.PLATFORM_NAMES,
        "samples": samples,
    }
    js = (
        "/* Generated by tools/gen_web_data.py from scvr/catalog.py and examples/.\n"
        " * Do not edit by hand -- regenerate instead. */\n"
        "(function (root) {\n"
        "  var data = " + json.dumps(body, indent=2, sort_keys=False) + ";\n"
        "  if (typeof module === 'object' && module.exports) { module.exports = data; }\n"
        "  else { root.CaptureData = data; }\n"
        "})(typeof self !== 'undefined' ? self : this);\n"
    )
    CATALOG_OUT.parent.mkdir(parents=True, exist_ok=True)
    CATALOG_OUT.write_text(js, encoding="utf-8")
    print(f"wrote {CATALOG_OUT} ({CATALOG_OUT.stat().st_size:,} bytes)")


def fixture_for(path: str) -> dict:
    engagement = Engagement.load(ROOT / path)
    # No library: parity is about the models, and the benchmark is exercised
    # separately in tests/test_library.py.
    audit = run(engagement, library_path=ROOT / "tests" / "fixtures" / "_absent.jsonl")
    return {
        "source": path,
        "engagement": json.loads((ROOT / path).read_text(encoding="utf-8")),
        "expected": {
            "capture_rate": audit.adoption.capture_rate,
            "catalog_capture_rate": audit.adoption.catalog_capture_rate,
            "assessment_coverage": audit.adoption.assessment_coverage,
            "license_waste_share": audit.adoption.license_waste_share(),
            "dormant": [line.capability.id for line in audit.adoption.dormant()],
            "by_module": {
                module: row["capture_rate"] for module, row in audit.adoption.by_module().items()
            },
            "qualification": {
                "verdict": audit.qualification.verdict,
                "checks": {c.id: c.verdict for c in audit.qualification.checks},
            },
            "leakage": {
                "gross_total": audit.leakage.gross_total,
                "recoverable_total": audit.leakage.recoverable_total,
                "recoverable_low": audit.leakage.recoverable_low,
                "recoverable_high": audit.leakage.recoverable_high,
                "license_waste": audit.leakage.license_waste,
                "estimates": {
                    e.model_id: {
                        "gross": e.gross_annual,
                        "recoverable": e.recoverable_annual,
                        "low": e.low,
                        "high": e.high,
                        "confidence": e.confidence,
                        "evidence": e.evidence,
                    }
                    for e in audit.leakage.estimates
                },
                "skipped": sorted(s.model_id for s in audit.leakage.skipped),
            },
            "roadmap": {
                "sprint_items": [i.id for i in audit.roadmap.sprint.items],
                "duration_weeks": audit.roadmap.sprint.duration_weeks,
                "team_size": audit.roadmap.sprint.team_size,
                "effort_weeks": audit.roadmap.sprint.effort_weeks,
                "sprint_recoverable": audit.roadmap.sprint.recoverable_annual,
                "item_effort": {i.id: i.effort_weeks for i in audit.roadmap.items},
                "item_score": {i.id: i.score for i in audit.roadmap.items},
                "unquantified": [i.id for i in audit.roadmap.unquantified],
            },
            "commercials": {
                "audit_fee": audit.commercials.audit_fee,
                "sprint_fee": audit.commercials.sprint_fee,
                "retainer_monthly": audit.commercials.retainer_monthly,
                "sprint_margin": audit.commercials.sprint_margin,
                "year_one_multiple": audit.commercials.year_one_multiple,
            },
        },
    }


def market_fixtures() -> list[dict]:
    from scvr import economics, market

    metros, _ = market.load_markets()
    industries = json.loads((ROOT / "data" / "metro-markets.json").read_text())["industries"]
    by_name = {}
    for city in ["Dallas", "Atlanta", "Riverside", "Chicago", "Toledo", "New York"]:
        found = market.find_metro(metros, city)
        if found:
            by_name[city] = found

    cases = []
    for label, cities, overrides, firm_overrides in [
        ("dallas-solo", ["Dallas"], {}, {"consultants": 2}),
        ("dallas-atlanta", ["Dallas", "Atlanta"], {}, {"consultants": 2}),
        ("thin-metro", ["Toledo"], {}, {"consultants": 2}),
        ("big-team", ["Dallas", "Riverside", "Chicago"],
         {"starting_consultants": 4, "sellers": 2}, {"consultants": 4}),
        ("cold-chain-focus", ["Chicago"], {"sub_vertical": "cold_chain"}, {"consultants": 2}),
        ("long-terms", ["New York"], {}, {"consultants": 2, "payment_terms_days": 90,
                                          "deposit_rate": 0.2, "starting_cash": 50_000}),
    ]:
        ids = [by_name[c].id for c in cities if c in by_name]
        firm = economics.FirmModel(**firm_overrides)
        inputs = market.ScenarioInputs(markets=ids, horizon_months=36, **overrides)
        scenario = market.run_scenario(metros, firm, inputs, industries=industries)
        cases.append({
            "label": label,
            "market_ids": ids,
            "inputs": {k: v for k, v in overrides.items()},
            "firm_overrides": firm_overrides,
            "expected": {
                "verdict": scenario.verdict,
                "reasons": scenario.reasons,
                "breakeven_month": scenario.breakeven_month,
                "cash_trough": scenario.cash_trough,
                "cash_trough_month": scenario.cash_trough_month,
                "peak_consultants": scenario.peak_consultants,
                "year_three_revenue": scenario.year_three_revenue,
                "total_revenue": scenario.total_revenue,
                "addressable": scenario.addressable,
                "market_exhausted_month": scenario.market_exhausted_month,
                "months": [
                    {"month": mo.month, "revenue": mo.revenue, "profit": mo.profit,
                     "cumulative_profit": mo.cumulative_profit, "cash": mo.cash,
                     "consultants": mo.consultants, "utilization": mo.utilization,
                     "audits_signed": mo.audits_signed}
                    for mo in scenario.months
                ],
            },
        })

    sizings = []
    for city in ["Dallas", "Toledo", "New York"]:
        found = by_name.get(city)
        if not found:
            continue
        for sub in [None, "3pl", "cold_chain"]:
            sized = market.size_market(found, None, sub, industries)
            sizings.append({
                "metro_id": found.id, "sub_vertical": sub,
                "expected": {
                    "enterprise_sites": sized.enterprise_sites,
                    "platform_accounts": sized.platform_accounts,
                    "addressable": sized.addressable,
                    "disclosed_employment": sized.disclosed_employment,
                },
            })

    ranked = market.rank_markets(metros, None, "3pl", industries, limit=8)
    return [{
        "scenarios": cases,
        "sizings": sizings,
        "ranking_3pl": [s.metro.id for s in ranked],
        "lookups": {q: (market.find_metro(metros, q).id if market.find_metro(metros, q) else None)
                    for q in ["Dallas", "dallas-fort worth", "C1910", "Riverside", "nowhere city"]},
    }]


def write_fixtures() -> None:
    from scvr import economics

    firms = [
        {},
        {"consultants": 2, "audits_per_year": 4, "sprints_per_year": 2, "retainer_clients": 0,
         "starting_cash": 60_000},
        {"consultants": 6, "audits_per_year": 8, "sprints_per_year": 4, "retainer_clients": 4,
         "payment_terms_days": 90, "deposit_rate": 0.25},
    ]
    firm_cases = []
    for overrides in firms:
        firm = economics.FirmModel(**overrides)
        econ = economics.unit_economics(firm)
        cash = economics.cash_flow(firm, 24)
        firm_cases.append(
            {
                "overrides": overrides,
                "expected": {
                    "revenue": econ.revenue,
                    "delivery_cost": econ.delivery_cost,
                    "gross_margin": econ.gross_margin,
                    "operating_profit": econ.operating_profit,
                    "required_weeks": econ.required_weeks,
                    "implied_utilization": econ.implied_utilization,
                    "recurring_share": econ.recurring_share,
                    "breakeven_audits": econ.breakeven_audits,
                    "warnings": len(econ.warnings),
                    "min_balance": cash.min_balance,
                    "trough_month": cash.trough_month,
                    "ending_balance": cash.ending_balance,
                    "months_negative": cash.months_negative,
                    "credit_line_needed": cash.credit_line_needed,
                },
            }
        )

    payload = {
        "generated_by": "tools/gen_web_data.py",
        "audits": [fixture_for(path) for path in EXAMPLES],
        "firms": firm_cases,
        "market": market_fixtures()[0],
    }
    FIXTURE_OUT.parent.mkdir(parents=True, exist_ok=True)
    FIXTURE_OUT.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {FIXTURE_OUT} ({FIXTURE_OUT.stat().st_size:,} bytes)")


if __name__ == "__main__":
    write_catalog_js()
    write_fixtures()
