#!/usr/bin/env python3
"""Build the embedded display face for the web console.

Bitstream Charter ships on most Linux boxes as Type 1 only. The Artifact CSP
blocks font CDNs, so the face has to travel inside the HTML: this converts the
Type 1 outlines to a subsetted WOFF2 and writes a stylesheet of @font-face
rules with the payload inlined as data URIs.

Run only when the character set or the source font changes; the generated
`web/src/fonts.css` is committed so the normal build has no font dependency.

    python3 tools/subset_fonts.py
"""

from __future__ import annotations

import base64
import io
from pathlib import Path

from fontTools import t1Lib
from fontTools.agl import UV2AGL
from fontTools.fontBuilder import FontBuilder
from fontTools.pens.boundsPen import BoundsPen
from fontTools.pens.t2CharStringPen import T2CharStringPen

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "web" / "src" / "fonts.css"

SOURCES = [
    ("Charter", 400, "normal", "/usr/share/fonts/X11/Type1/c0648bt_.pfb"),
    ("Charter", 700, "normal", "/usr/share/fonts/X11/Type1/c0632bt_.pfb"),
    ("Charter", 400, "italic", "/usr/share/fonts/X11/Type1/c0649bt_.pfb"),
]

# Everything the console renders in the display face, and nothing else.
CHARSET = (
    " !\"#$%&'()*+,-./0123456789:;<=>?@"
    "ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`"
    "abcdefghijklmnopqrstuvwxyz{|}~"
    "–—‘’“”…·×±£€"
)


def convert(path: str, family: str, weight: int, style: str) -> bytes:
    source = t1Lib.T1Font(path)
    source.parse()
    glyph_set = source.getGlyphSet()

    order = [".notdef"]
    cmap: dict[int, str] = {}
    for char in CHARSET:
        name = UV2AGL.get(ord(char))
        if name is None or name not in glyph_set:
            continue
        cmap[ord(char)] = name
        if name not in order:
            order.append(name)

    upem = 1000
    builder = FontBuilder(unitsPerEm=upem, isTTF=False)
    builder.setupGlyphOrder(order)
    builder.setupCharacterMap(cmap)

    charstrings = {}
    metrics = {}
    for name in order:
        pen = T2CharStringPen(None, None)
        bounds_pen = BoundsPen(glyph_set)
        width = 0
        if name in glyph_set:
            glyph = glyph_set[name]
            glyph.draw(pen)
            glyph.draw(bounds_pen)
            width = int(round(getattr(glyph, "width", 0)))
        charstrings[name] = pen.getCharString()
        left = int(round(bounds_pen.bounds[0])) if bounds_pen.bounds else 0
        metrics[name] = (width, left)

    style_name = {400: "Regular", 700: "Bold"}[weight]
    if style == "italic":
        style_name = "Italic" if weight == 400 else f"Bold Italic"

    builder.setupCFF(
        f"{family}-{style_name.replace(' ', '')}",
        {"FullName": f"{family} {style_name}", "FamilyName": family, "Weight": style_name},
        charstrings,
        {},
    )
    builder.setupHorizontalMetrics(metrics)
    builder.setupHorizontalHeader(ascent=760, descent=-240, lineGap=0)
    builder.setupNameTable(
        {
            "familyName": family,
            "styleName": style_name,
            "psName": f"{family}-{style_name.replace(' ', '')}",
            "version": "1.0",
        }
    )
    builder.setupOS2(sTypoAscender=760, sTypoDescender=-240, usWinAscent=760, usWinDescent=240)
    builder.setupPost(isFixedPitch=0)

    builder.font.flavor = "woff2"
    buffer = io.BytesIO()
    builder.save(buffer)
    return buffer.getvalue()


def main() -> None:
    rules = [
        "/* Generated by tools/subset_fonts.py -- do not edit by hand.",
        " * Bitstream Charter (Matthew Carter, 1987), released by Bitstream for",
        " * free use. Converted from Type 1, subsetted, and inlined because the",
        " * Artifact content security policy blocks external font requests.",
        " */",
    ]
    total = 0
    for family, weight, style, path in SOURCES:
        if not Path(path).exists():
            print(f"skip {path} (not present)")
            continue
        payload = convert(path, family, weight, style)
        total += len(payload)
        encoded = base64.b64encode(payload).decode("ascii")
        rules.append(
            "@font-face {\n"
            f"  font-family: '{family}';\n"
            f"  font-style: {style};\n"
            f"  font-weight: {weight};\n"
            "  font-display: swap;\n"
            f"  src: url(data:font/woff2;base64,{encoded}) format('woff2');\n"
            "}"
        )
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(rules) + "\n", encoding="utf-8")
    print(f"wrote {OUT} ({total:,} bytes of font, {OUT.stat().st_size:,} bytes of CSS)")


if __name__ == "__main__":
    main()
