/* Generated by tools/gen_web_data.py from scvr/catalog.py and examples/.
 * Do not edit by hand -- regenerate instead. */
(function (root) {
  var data = {
  "catalogs": {
    "blue_yonder": [
      {
        "id": "by.dp.stat_forecast",
        "name": "Statistical forecasting",
        "module": "Demand Planning",
        "platform": "blue_yonder",
        "value_weight": 5,
        "value_driver": "inventory",
        "typical_capture": 0.82,
        "activation_effort_weeks": 2.0,
        "prerequisites": [],
        "data_requirements": [
          "shipment history",
          "product hierarchy"
        ]
      },
      {
        "id": "by.dp.demand_sensing",
        "name": "ML demand sensing (short horizon)",
        "module": "Demand Planning",
        "platform": "blue_yonder",
        "value_weight": 4,
        "value_driver": "inventory",
        "typical_capture": 0.31,
        "activation_effort_weeks": 5.0,
        "prerequisites": [
          "by.dp.stat_forecast"
        ],
        "data_requirements": [
          "POS or DC withdrawal feed",
          "open orders"
        ]
      },
      {
        "id": "by.dp.npi",
        "name": "New product introduction / like-modeling",
        "module": "Demand Planning",
        "platform": "blue_yonder",
        "value_weight": 3,
        "value_driver": "inventory",
        "typical_capture": 0.24,
        "activation_effort_weeks": 3.0,
        "prerequisites": [
          "by.dp.stat_forecast"
        ],
        "data_requirements": [
          "attribute master",
          "launch calendar"
        ]
      },
      {
        "id": "by.dp.promo",
        "name": "Promotion & event modeling",
        "module": "Demand Planning",
        "platform": "blue_yonder",
        "value_weight": 3,
        "value_driver": "margin",
        "typical_capture": 0.29,
        "activation_effort_weeks": 4.0,
        "prerequisites": [
          "by.dp.stat_forecast"
        ],
        "data_requirements": [
          "promo calendar",
          "lift history"
        ]
      },
      {
        "id": "by.dp.segmentation",
        "name": "Demand segmentation & model selection",
        "module": "Demand Planning",
        "platform": "blue_yonder",
        "value_weight": 3,
        "value_driver": "inventory",
        "typical_capture": 0.35,
        "activation_effort_weeks": 2.0,
        "prerequisites": [
          "by.dp.stat_forecast"
        ],
        "data_requirements": [
          "volume/variability classification"
        ]
      },
      {
        "id": "by.io.meio",
        "name": "Multi-echelon inventory optimization",
        "module": "Inventory Optimization",
        "platform": "blue_yonder",
        "value_weight": 5,
        "value_driver": "inventory",
        "typical_capture": 0.27,
        "activation_effort_weeks": 8.0,
        "prerequisites": [
          "by.dp.stat_forecast",
          "by.sp.master_planning"
        ],
        "data_requirements": [
          "network model",
          "lead time variability",
          "service targets by segment"
        ]
      },
      {
        "id": "by.io.safety_stock",
        "name": "Dynamic safety stock policy",
        "module": "Inventory Optimization",
        "platform": "blue_yonder",
        "value_weight": 4,
        "value_driver": "inventory",
        "typical_capture": 0.44,
        "activation_effort_weeks": 3.0,
        "prerequisites": [
          "by.dp.stat_forecast"
        ],
        "data_requirements": [
          "lead time by item/site",
          "service targets"
        ]
      },
      {
        "id": "by.sp.master_planning",
        "name": "Master supply planning",
        "module": "Supply Planning",
        "platform": "blue_yonder",
        "value_weight": 5,
        "value_driver": "service",
        "typical_capture": 0.71,
        "activation_effort_weeks": 4.0,
        "prerequisites": [],
        "data_requirements": [
          "BOM/routing or sourcing rules",
          "capacity calendars"
        ]
      },
      {
        "id": "by.sp.capacity",
        "name": "Constrained capacity planning",
        "module": "Supply Planning",
        "platform": "blue_yonder",
        "value_weight": 4,
        "value_driver": "service",
        "typical_capture": 0.38,
        "activation_effort_weeks": 5.0,
        "prerequisites": [
          "by.sp.master_planning"
        ],
        "data_requirements": [
          "resource capacity",
          "run rates"
        ]
      },
      {
        "id": "by.sp.sop",
        "name": "S&OP / integrated business planning cycle",
        "module": "Supply Planning",
        "platform": "blue_yonder",
        "value_weight": 4,
        "value_driver": "cycle_time",
        "typical_capture": 0.41,
        "activation_effort_weeks": 6.0,
        "prerequisites": [
          "by.dp.stat_forecast",
          "by.sp.master_planning"
        ],
        "data_requirements": [
          "financial plan alignment",
          "scenario definitions"
        ]
      },
      {
        "id": "by.ct.exception_mgmt",
        "name": "Control tower exception management",
        "module": "Luminate Control Tower",
        "platform": "blue_yonder",
        "value_weight": 5,
        "value_driver": "labor",
        "typical_capture": 0.22,
        "activation_effort_weeks": 4.0,
        "prerequisites": [
          "by.sp.master_planning"
        ],
        "data_requirements": [
          "alert thresholds",
          "ownership matrix"
        ]
      },
      {
        "id": "by.ct.playbooks",
        "name": "Resolution playbooks / automated disposition",
        "module": "Luminate Control Tower",
        "platform": "blue_yonder",
        "value_weight": 4,
        "value_driver": "labor",
        "typical_capture": 0.11,
        "activation_effort_weeks": 6.0,
        "prerequisites": [
          "by.ct.exception_mgmt"
        ],
        "data_requirements": [
          "documented resolution paths"
        ]
      },
      {
        "id": "by.ct.visibility",
        "name": "Multi-party shipment visibility",
        "module": "Luminate Control Tower",
        "platform": "blue_yonder",
        "value_weight": 3,
        "value_driver": "service",
        "typical_capture": 0.33,
        "activation_effort_weeks": 4.0,
        "prerequisites": [],
        "data_requirements": [
          "carrier EDI 214 / API feeds"
        ]
      },
      {
        "id": "by.tms.load_build",
        "name": "Load building & consolidation",
        "module": "Transportation Management",
        "platform": "blue_yonder",
        "value_weight": 4,
        "value_driver": "freight",
        "typical_capture": 0.48,
        "activation_effort_weeks": 4.0,
        "prerequisites": [],
        "data_requirements": [
          "order profile",
          "equipment master"
        ]
      },
      {
        "id": "by.tms.routing",
        "name": "Route optimization",
        "module": "Transportation Management",
        "platform": "blue_yonder",
        "value_weight": 4,
        "value_driver": "freight",
        "typical_capture": 0.42,
        "activation_effort_weeks": 5.0,
        "prerequisites": [
          "by.tms.load_build"
        ],
        "data_requirements": [
          "stop geocoding",
          "service windows"
        ]
      },
      {
        "id": "by.tms.rate_engine",
        "name": "Freight rate engine & least-cost carrier select",
        "module": "Transportation Management",
        "platform": "blue_yonder",
        "value_weight": 4,
        "value_driver": "freight",
        "typical_capture": 0.39,
        "activation_effort_weeks": 5.0,
        "prerequisites": [],
        "data_requirements": [
          "carrier contract rates",
          "accessorial schedules"
        ]
      },
      {
        "id": "by.tms.tendering",
        "name": "Automated tendering (EDI 204/990)",
        "module": "Transportation Management",
        "platform": "blue_yonder",
        "value_weight": 3,
        "value_driver": "freight",
        "typical_capture": 0.36,
        "activation_effort_weeks": 3.0,
        "prerequisites": [
          "by.tms.rate_engine"
        ],
        "data_requirements": [
          "carrier EDI trading partner setup"
        ]
      },
      {
        "id": "by.wms.labor_mgmt",
        "name": "Labor management & engineered standards",
        "module": "Warehouse Management",
        "platform": "blue_yonder",
        "value_weight": 4,
        "value_driver": "labor",
        "typical_capture": 0.26,
        "activation_effort_weeks": 6.0,
        "prerequisites": [],
        "data_requirements": [
          "engineered standards",
          "task-level scan data"
        ]
      },
      {
        "id": "by.wms.slotting",
        "name": "Slotting optimization",
        "module": "Warehouse Management",
        "platform": "blue_yonder",
        "value_weight": 3,
        "value_driver": "labor",
        "typical_capture": 0.19,
        "activation_effort_weeks": 4.0,
        "prerequisites": [],
        "data_requirements": [
          "velocity data",
          "slot dimensions"
        ]
      },
      {
        "id": "by.oms.atp",
        "name": "Available-to-promise / order sourcing",
        "module": "Order Management",
        "platform": "blue_yonder",
        "value_weight": 4,
        "value_driver": "service",
        "typical_capture": 0.34,
        "activation_effort_weeks": 5.0,
        "prerequisites": [
          "by.sp.master_planning"
        ],
        "data_requirements": [
          "real-time inventory positions"
        ]
      }
    ],
    "kinaxis": [
      {
        "id": "kx.dp.stat_forecast",
        "name": "Statistical forecasting",
        "module": "Demand Planning",
        "platform": "kinaxis",
        "value_weight": 5,
        "value_driver": "inventory",
        "typical_capture": 0.78,
        "activation_effort_weeks": 2.0,
        "prerequisites": [],
        "data_requirements": [
          "shipment history",
          "product hierarchy"
        ]
      },
      {
        "id": "kx.dp.consensus",
        "name": "Consensus demand & override capture",
        "module": "Demand Planning",
        "platform": "kinaxis",
        "value_weight": 4,
        "value_driver": "cycle_time",
        "typical_capture": 0.48,
        "activation_effort_weeks": 3.0,
        "prerequisites": [
          "kx.dp.stat_forecast"
        ],
        "data_requirements": [
          "sales input cadence"
        ]
      },
      {
        "id": "kx.sp.constrained",
        "name": "Constrained supply planning",
        "module": "Supply Planning",
        "platform": "kinaxis",
        "value_weight": 5,
        "value_driver": "service",
        "typical_capture": 0.69,
        "activation_effort_weeks": 4.0,
        "prerequisites": [],
        "data_requirements": [
          "BOM/routing",
          "capacity calendars"
        ]
      },
      {
        "id": "kx.sp.aggregate",
        "name": "Aggregate / rough-cut capacity planning",
        "module": "Supply Planning",
        "platform": "kinaxis",
        "value_weight": 4,
        "value_driver": "service",
        "typical_capture": 0.41,
        "activation_effort_weeks": 4.0,
        "prerequisites": [
          "kx.sp.constrained"
        ],
        "data_requirements": [
          "resource capacity"
        ]
      },
      {
        "id": "kx.sp.clear_to_build",
        "name": "Clear-to-build / shortage analysis",
        "module": "Supply Planning",
        "platform": "kinaxis",
        "value_weight": 4,
        "value_driver": "service",
        "typical_capture": 0.35,
        "activation_effort_weeks": 4.0,
        "prerequisites": [
          "kx.sp.constrained"
        ],
        "data_requirements": [
          "component pegging",
          "on-hand accuracy"
        ]
      },
      {
        "id": "kx.io.meio",
        "name": "Multi-echelon inventory optimization",
        "module": "Inventory Optimization",
        "platform": "kinaxis",
        "value_weight": 5,
        "value_driver": "inventory",
        "typical_capture": 0.23,
        "activation_effort_weeks": 8.0,
        "prerequisites": [
          "kx.dp.stat_forecast",
          "kx.sp.constrained"
        ],
        "data_requirements": [
          "network model",
          "lead time variability",
          "service targets"
        ]
      },
      {
        "id": "kx.io.safety_stock",
        "name": "Safety stock policy management",
        "module": "Inventory Optimization",
        "platform": "kinaxis",
        "value_weight": 4,
        "value_driver": "inventory",
        "typical_capture": 0.45,
        "activation_effort_weeks": 3.0,
        "prerequisites": [
          "kx.dp.stat_forecast"
        ],
        "data_requirements": [
          "lead time by item/site"
        ]
      },
      {
        "id": "kx.sim.scenario",
        "name": "Scenario simulation (what-if)",
        "module": "Simulation",
        "platform": "kinaxis",
        "value_weight": 5,
        "value_driver": "cycle_time",
        "typical_capture": 0.39,
        "activation_effort_weeks": 3.0,
        "prerequisites": [
          "kx.sp.constrained"
        ],
        "data_requirements": [
          "scenario library",
          "baseline snapshots"
        ]
      },
      {
        "id": "kx.sim.compare",
        "name": "Scenario comparison & decision logging",
        "module": "Simulation",
        "platform": "kinaxis",
        "value_weight": 3,
        "value_driver": "cycle_time",
        "typical_capture": 0.21,
        "activation_effort_weeks": 3.0,
        "prerequisites": [
          "kx.sim.scenario"
        ],
        "data_requirements": [
          "decision rights",
          "audit trail policy"
        ]
      },
      {
        "id": "kx.sop.cycle",
        "name": "S&OP cycle orchestration",
        "module": "S&OP",
        "platform": "kinaxis",
        "value_weight": 4,
        "value_driver": "cycle_time",
        "typical_capture": 0.43,
        "activation_effort_weeks": 6.0,
        "prerequisites": [
          "kx.dp.consensus",
          "kx.sp.constrained"
        ],
        "data_requirements": [
          "cycle calendar"
        ]
      },
      {
        "id": "kx.ct.alerts",
        "name": "Alert-based exception management",
        "module": "Control Tower",
        "platform": "kinaxis",
        "value_weight": 5,
        "value_driver": "labor",
        "typical_capture": 0.26,
        "activation_effort_weeks": 4.0,
        "prerequisites": [
          "kx.sp.constrained"
        ],
        "data_requirements": [
          "alert thresholds",
          "ownership matrix"
        ]
      },
      {
        "id": "kx.ct.playbooks",
        "name": "Automated exception disposition",
        "module": "Control Tower",
        "platform": "kinaxis",
        "value_weight": 4,
        "value_driver": "labor",
        "typical_capture": 0.12,
        "activation_effort_weeks": 6.0,
        "prerequisites": [
          "kx.ct.alerts"
        ],
        "data_requirements": [
          "documented resolution paths"
        ]
      },
      {
        "id": "kx.of.atp",
        "name": "Order fulfillment / ATP",
        "module": "Order Fulfillment",
        "platform": "kinaxis",
        "value_weight": 4,
        "value_driver": "service",
        "typical_capture": 0.32,
        "activation_effort_weeks": 5.0,
        "prerequisites": [
          "kx.sp.constrained"
        ],
        "data_requirements": [
          "real-time inventory positions"
        ]
      },
      {
        "id": "kx.an.analytics",
        "name": "Planner analytics & KPI dashboards",
        "module": "Analytics",
        "platform": "kinaxis",
        "value_weight": 3,
        "value_driver": "cycle_time",
        "typical_capture": 0.55,
        "activation_effort_weeks": 2.0,
        "prerequisites": [],
        "data_requirements": [
          "KPI definitions",
          "baseline period"
        ]
      },
      {
        "id": "kx.dm.data_quality",
        "name": "Data quality monitoring & exception feeds",
        "module": "Data Management",
        "platform": "kinaxis",
        "value_weight": 4,
        "value_driver": "data",
        "typical_capture": 0.3,
        "activation_effort_weeks": 4.0,
        "prerequisites": [],
        "data_requirements": [
          "master data ownership",
          "error thresholds"
        ]
      }
    ],
    "o9": [
      {
        "id": "o9.dp.stat_forecast",
        "name": "Statistical forecasting engine",
        "module": "Demand Planning",
        "platform": "o9",
        "value_weight": 5,
        "value_driver": "inventory",
        "typical_capture": 0.8,
        "activation_effort_weeks": 2.0,
        "prerequisites": [],
        "data_requirements": [
          "shipment history",
          "product hierarchy"
        ]
      },
      {
        "id": "o9.dp.demand_sensing",
        "name": "Demand sensing",
        "module": "Demand Planning",
        "platform": "o9",
        "value_weight": 4,
        "value_driver": "inventory",
        "typical_capture": 0.28,
        "activation_effort_weeks": 5.0,
        "prerequisites": [
          "o9.dp.stat_forecast"
        ],
        "data_requirements": [
          "POS/channel feed",
          "open orders"
        ]
      },
      {
        "id": "o9.dp.attribute_forecast",
        "name": "Attribute-based / NPI forecasting",
        "module": "Demand Planning",
        "platform": "o9",
        "value_weight": 3,
        "value_driver": "inventory",
        "typical_capture": 0.22,
        "activation_effort_weeks": 4.0,
        "prerequisites": [
          "o9.dp.stat_forecast"
        ],
        "data_requirements": [
          "attribute master"
        ]
      },
      {
        "id": "o9.dp.consensus",
        "name": "Consensus demand workflow",
        "module": "Demand Planning",
        "platform": "o9",
        "value_weight": 4,
        "value_driver": "cycle_time",
        "typical_capture": 0.46,
        "activation_effort_weeks": 3.0,
        "prerequisites": [
          "o9.dp.stat_forecast"
        ],
        "data_requirements": [
          "sales input cadence",
          "override capture"
        ]
      },
      {
        "id": "o9.sp.constrained",
        "name": "Constrained supply planning",
        "module": "Supply Planning",
        "platform": "o9",
        "value_weight": 5,
        "value_driver": "service",
        "typical_capture": 0.63,
        "activation_effort_weeks": 5.0,
        "prerequisites": [],
        "data_requirements": [
          "sourcing rules",
          "capacity model"
        ]
      },
      {
        "id": "o9.sp.capacity",
        "name": "Capacity & resource planning",
        "module": "Supply Planning",
        "platform": "o9",
        "value_weight": 4,
        "value_driver": "service",
        "typical_capture": 0.37,
        "activation_effort_weeks": 5.0,
        "prerequisites": [
          "o9.sp.constrained"
        ],
        "data_requirements": [
          "resource master",
          "run rates"
        ]
      },
      {
        "id": "o9.sp.allocation",
        "name": "Supply allocation / fair share",
        "module": "Supply Planning",
        "platform": "o9",
        "value_weight": 3,
        "value_driver": "service",
        "typical_capture": 0.29,
        "activation_effort_weeks": 4.0,
        "prerequisites": [
          "o9.sp.constrained"
        ],
        "data_requirements": [
          "customer priority tiers"
        ]
      },
      {
        "id": "o9.io.meio",
        "name": "Multi-echelon inventory optimization",
        "module": "Inventory Optimization",
        "platform": "o9",
        "value_weight": 5,
        "value_driver": "inventory",
        "typical_capture": 0.25,
        "activation_effort_weeks": 8.0,
        "prerequisites": [
          "o9.dp.stat_forecast",
          "o9.sp.constrained"
        ],
        "data_requirements": [
          "network model",
          "lead time variability",
          "service targets"
        ]
      },
      {
        "id": "o9.ibp.scenario",
        "name": "Scenario planning / what-if simulation",
        "module": "IBP",
        "platform": "o9",
        "value_weight": 5,
        "value_driver": "cycle_time",
        "typical_capture": 0.33,
        "activation_effort_weeks": 4.0,
        "prerequisites": [
          "o9.sp.constrained"
        ],
        "data_requirements": [
          "scenario library",
          "baseline snapshots"
        ]
      },
      {
        "id": "o9.ibp.pnl_sim",
        "name": "P&L simulation of supply scenarios",
        "module": "IBP",
        "platform": "o9",
        "value_weight": 4,
        "value_driver": "margin",
        "typical_capture": 0.18,
        "activation_effort_weeks": 6.0,
        "prerequisites": [
          "o9.ibp.scenario"
        ],
        "data_requirements": [
          "cost model",
          "price/margin by SKU"
        ]
      },
      {
        "id": "o9.ibp.sop_cycle",
        "name": "Executive S&OP cycle orchestration",
        "module": "IBP",
        "platform": "o9",
        "value_weight": 4,
        "value_driver": "cycle_time",
        "typical_capture": 0.44,
        "activation_effort_weeks": 6.0,
        "prerequisites": [
          "o9.dp.consensus",
          "o9.sp.constrained"
        ],
        "data_requirements": [
          "cycle calendar",
          "decision rights"
        ]
      },
      {
        "id": "o9.kg.knowledge_graph",
        "name": "Enterprise knowledge graph modeling",
        "module": "Digital Brain",
        "platform": "o9",
        "value_weight": 5,
        "value_driver": "data",
        "typical_capture": 0.36,
        "activation_effort_weeks": 8.0,
        "prerequisites": [],
        "data_requirements": [
          "master data governance",
          "integration contracts"
        ]
      },
      {
        "id": "o9.ct.exception_mgmt",
        "name": "Control tower exceptions & alerts",
        "module": "Control Tower",
        "platform": "o9",
        "value_weight": 5,
        "value_driver": "labor",
        "typical_capture": 0.24,
        "activation_effort_weeks": 4.0,
        "prerequisites": [
          "o9.sp.constrained"
        ],
        "data_requirements": [
          "alert thresholds",
          "ownership matrix"
        ]
      },
      {
        "id": "o9.ct.playbooks",
        "name": "Automated resolution playbooks",
        "module": "Control Tower",
        "platform": "o9",
        "value_weight": 4,
        "value_driver": "labor",
        "typical_capture": 0.1,
        "activation_effort_weeks": 6.0,
        "prerequisites": [
          "o9.ct.exception_mgmt"
        ],
        "data_requirements": [
          "documented resolution paths"
        ]
      },
      {
        "id": "o9.rev.pricing",
        "name": "Revenue / price-volume planning",
        "module": "Revenue Management",
        "platform": "o9",
        "value_weight": 3,
        "value_driver": "margin",
        "typical_capture": 0.16,
        "activation_effort_weeks": 6.0,
        "prerequisites": [
          "o9.dp.stat_forecast"
        ],
        "data_requirements": [
          "price elasticity history"
        ]
      },
      {
        "id": "o9.an.analytics",
        "name": "Planner analytics & KPI cockpit",
        "module": "Analytics",
        "platform": "o9",
        "value_weight": 3,
        "value_driver": "cycle_time",
        "typical_capture": 0.52,
        "activation_effort_weeks": 2.0,
        "prerequisites": [],
        "data_requirements": [
          "KPI definitions",
          "baseline period"
        ]
      }
    ]
  },
  "platformNames": {
    "blue_yonder": "Blue Yonder Luminate",
    "o9": "o9 Digital Brain",
    "kinaxis": "Kinaxis Maestro / RapidResponse"
  },
  "samples": [
    {
      "engagement_id": "northgate-3pl-2026-q1",
      "client": {
        "name": "Northgate Logistics",
        "platform": "blue_yonder",
        "sub_vertical": "3pl",
        "annual_revenue": 340000000,
        "live_months": 21,
        "sites": 6,
        "erp_systems": 2,
        "skus": 48000,
        "planners_fte": 9,
        "annual_license_fee": 620000,
        "implementation_spend": 3800000,
        "business_case_annual_benefit": 4200000
      },
      "capabilities": {
        "by.dp.stat_forecast": "full",
        "by.dp.demand_sensing": "licensed_unused",
        "by.dp.npi": "not_licensed",
        "by.dp.promo": "not_licensed",
        "by.dp.segmentation": "deployed_unused",
        "by.io.meio": "licensed_unused",
        "by.io.safety_stock": "partial",
        "by.sp.master_planning": "full",
        "by.sp.capacity": "partial",
        "by.sp.sop": "partial",
        "by.ct.exception_mgmt": "deployed_unused",
        "by.ct.playbooks": "licensed_unused",
        "by.ct.visibility": "partial",
        "by.tms.load_build": "full",
        "by.tms.routing": "partial",
        "by.tms.rate_engine": "deployed_unused",
        "by.tms.tendering": "licensed_unused",
        "by.wms.labor_mgmt": "licensed_unused",
        "by.wms.slotting": "not_licensed",
        "by.oms.atp": "deployed_unused"
      },
      "operations": {
        "annual_cogs": 268000000,
        "gross_margin_pct": 0.21,
        "inventory_value": 41000000,
        "carrying_cost_rate": 0.24,
        "excess_obsolete_writeoff": 1900000,
        "forecast_mape": 0.34,
        "attainable_mape": 0.24,
        "avg_lead_time_weeks": 5.5,
        "service_level_target": 0.95,
        "exceptions_per_week": 640,
        "minutes_per_exception": 11,
        "exception_automation_rate": 0.05,
        "planner_loaded_cost": 118000,
        "planner_override_rate": 0.58,
        "override_value_add_rate": 0.25,
        "annual_freight_spend": 22000000,
        "expedite_share": 0.14,
        "expedite_premium_pct": 0.38,
        "stockout_rate": 0.021,
        "otif_pct": 0.912,
        "master_data_accuracy": 0.88,
        "data_rework_hours_per_week": 26,
        "interface_failure_rate": 0.03
      },
      "governance": {
        "executive_sponsor": "VP Supply Chain",
        "documented_baseline": true,
        "baseline_period_months": 6,
        "dedicated_client_resource": true,
        "prior_remediation_attempts": 1,
        "vendor_relationship": "renewal_risk"
      },
      "evidence": {
        "default": "estimated",
        "exception_handling": "measured",
        "planner_override": "measured",
        "expedite_freight": "measured",
        "stockout_margin": "anecdotal"
      },
      "notes": "Client zero. Audit delivered at cost in exchange for a named case study. Blue Yonder CSM made the introduction ahead of a renewal conversation."
    },
    {
      "engagement_id": "harborlink-3pl-2025-q3",
      "client": {
        "name": "Harborlink Freight Services",
        "platform": "blue_yonder",
        "sub_vertical": "3pl",
        "annual_revenue": 290000000,
        "live_months": 30,
        "sites": 4,
        "erp_systems": 1,
        "skus": 22000,
        "planners_fte": 6,
        "annual_license_fee": 480000,
        "implementation_spend": 2600000,
        "business_case_annual_benefit": 3100000
      },
      "capabilities": {
        "by.dp.stat_forecast": "full",
        "by.dp.demand_sensing": "not_licensed",
        "by.dp.npi": "not_licensed",
        "by.dp.promo": "not_licensed",
        "by.dp.segmentation": "partial",
        "by.io.meio": "not_licensed",
        "by.io.safety_stock": "full",
        "by.sp.master_planning": "full",
        "by.sp.capacity": "partial",
        "by.sp.sop": "partial",
        "by.ct.exception_mgmt": "partial",
        "by.ct.playbooks": "licensed_unused",
        "by.ct.visibility": "full",
        "by.tms.load_build": "full",
        "by.tms.routing": "full",
        "by.tms.rate_engine": "partial",
        "by.tms.tendering": "deployed_unused",
        "by.wms.labor_mgmt": "deployed_unused",
        "by.wms.slotting": "licensed_unused",
        "by.oms.atp": "not_licensed"
      },
      "operations": {
        "annual_cogs": 231000000,
        "gross_margin_pct": 0.19,
        "inventory_value": 26000000,
        "carrying_cost_rate": 0.22,
        "forecast_mape": 0.27,
        "avg_lead_time_weeks": 4.0,
        "service_level_target": 0.95,
        "exceptions_per_week": 310,
        "minutes_per_exception": 9,
        "exception_automation_rate": 0.2,
        "planner_loaded_cost": 112000,
        "planner_override_rate": 0.34,
        "annual_freight_spend": 31000000,
        "expedite_share": 0.09,
        "master_data_accuracy": 0.93,
        "data_rework_hours_per_week": 11,
        "interface_failure_rate": 0.01
      },
      "governance": {
        "executive_sponsor": "COO",
        "documented_baseline": true,
        "baseline_period_months": 6,
        "dedicated_client_resource": true,
        "prior_remediation_attempts": 0,
        "vendor_relationship": "healthy"
      },
      "evidence": {
        "default": "estimated",
        "exception_handling": "measured",
        "expedite_freight": "measured"
      },
      "notes": "Illustrative comparable used to seed the pattern library."
    },
    {
      "engagement_id": "meridian-cold-chain-2025-q4",
      "client": {
        "name": "Meridian Cold Chain",
        "platform": "blue_yonder",
        "sub_vertical": "cold_chain",
        "annual_revenue": 185000000,
        "live_months": 16,
        "sites": 3,
        "erp_systems": 2,
        "skus": 9400,
        "planners_fte": 5,
        "annual_license_fee": 410000,
        "implementation_spend": 2200000,
        "business_case_annual_benefit": 2400000
      },
      "capabilities": {
        "by.dp.stat_forecast": "partial",
        "by.dp.demand_sensing": "licensed_unused",
        "by.dp.npi": "not_licensed",
        "by.dp.promo": "licensed_unused",
        "by.dp.segmentation": "licensed_unused",
        "by.io.meio": "licensed_unused",
        "by.io.safety_stock": "deployed_unused",
        "by.sp.master_planning": "partial",
        "by.sp.capacity": "licensed_unused",
        "by.sp.sop": "deployed_unused",
        "by.ct.exception_mgmt": "licensed_unused",
        "by.ct.playbooks": "licensed_unused",
        "by.ct.visibility": "partial",
        "by.tms.load_build": "partial",
        "by.tms.routing": "deployed_unused",
        "by.tms.rate_engine": "licensed_unused",
        "by.tms.tendering": "not_licensed",
        "by.wms.labor_mgmt": "not_licensed",
        "by.wms.slotting": "not_licensed",
        "by.oms.atp": "not_licensed"
      },
      "operations": {
        "annual_cogs": 142000000,
        "gross_margin_pct": 0.24,
        "inventory_value": 19000000,
        "carrying_cost_rate": 0.31,
        "excess_obsolete_writeoff": 2800000,
        "forecast_mape": 0.41,
        "avg_lead_time_weeks": 3.0,
        "service_level_target": 0.98,
        "exceptions_per_week": 420,
        "minutes_per_exception": 14,
        "planner_loaded_cost": 104000,
        "planner_override_rate": 0.71,
        "annual_freight_spend": 17000000,
        "expedite_share": 0.19,
        "stockout_rate": 0.034,
        "master_data_accuracy": 0.86,
        "data_rework_hours_per_week": 33
      },
      "governance": {
        "executive_sponsor": "VP Operations",
        "documented_baseline": false,
        "baseline_period_months": 0,
        "dedicated_client_resource": false,
        "prior_remediation_attempts": 1,
        "vendor_relationship": "renewal_risk"
      },
      "evidence": {
        "default": "estimated",
        "excess_obsolete": "measured",
        "stockout_margin": "anecdotal"
      },
      "notes": "Illustrative comparable used to seed the pattern library. Short shelf life amplifies forecast error into write-off."
    },
    {
      "engagement_id": "valeron-distribution-2026-q1",
      "client": {
        "name": "Valeron Industrial Distribution",
        "platform": "blue_yonder",
        "sub_vertical": "industrial_distribution",
        "annual_revenue": 760000000,
        "live_months": 26,
        "sites": 11,
        "erp_systems": 3,
        "skus": 132000,
        "planners_fte": 17,
        "annual_license_fee": 1150000,
        "implementation_spend": 7400000,
        "business_case_annual_benefit": 9100000
      },
      "capabilities": {
        "by.dp.stat_forecast": "full",
        "by.dp.demand_sensing": "deployed_unused",
        "by.dp.npi": "partial",
        "by.dp.promo": "partial",
        "by.dp.segmentation": "full",
        "by.io.meio": "deployed_unused",
        "by.io.safety_stock": "full",
        "by.sp.master_planning": "full",
        "by.sp.capacity": "full",
        "by.sp.sop": "full",
        "by.ct.exception_mgmt": "partial",
        "by.ct.playbooks": "deployed_unused",
        "by.ct.visibility": "partial",
        "by.tms.load_build": "partial",
        "by.tms.routing": "licensed_unused",
        "by.tms.rate_engine": "partial",
        "by.tms.tendering": "partial",
        "by.wms.labor_mgmt": "partial",
        "by.wms.slotting": "deployed_unused",
        "by.oms.atp": "partial"
      },
      "operations": {
        "annual_cogs": 574000000,
        "gross_margin_pct": 0.28,
        "inventory_value": 96000000,
        "carrying_cost_rate": 0.2,
        "excess_obsolete_writeoff": 4100000,
        "forecast_mape": 0.23,
        "attainable_mape": 0.18,
        "avg_lead_time_weeks": 7.0,
        "service_level_target": 0.96,
        "exceptions_per_week": 980,
        "minutes_per_exception": 8,
        "exception_automation_rate": 0.35,
        "planner_loaded_cost": 126000,
        "planner_override_rate": 0.29,
        "override_value_add_rate": 0.35,
        "annual_freight_spend": 48000000,
        "expedite_share": 0.07,
        "stockout_rate": 0.014,
        "otif_pct": 0.947,
        "master_data_accuracy": 0.94,
        "data_rework_hours_per_week": 18,
        "interface_failure_rate": 0.02
      },
      "governance": {
        "executive_sponsor": "VP Supply Chain",
        "documented_baseline": true,
        "baseline_period_months": 12,
        "dedicated_client_resource": true,
        "prior_remediation_attempts": 0,
        "vendor_relationship": "healthy"
      },
      "evidence": {
        "default": "measured",
        "stockout_margin": "estimated"
      },
      "notes": "Illustrative comparable used to seed the pattern library. Mature deployment; the gap is depth of use in TMS and control tower, not breadth."
    }
  ]
};
  if (typeof module === 'object' && module.exports) { module.exports = data; }
  else { root.CaptureData = data; }
})(typeof self !== 'undefined' ? self : this);
